export const KNOWN_NAMES = [
    ' ',
    '  ',
    'xxx',

    'bg',
    'vs',
    'xp',
    'all',
    'air',
    'bow',
    'box',
    'buy',
    'env',
    'fog',
    'inv',
    'law',
    'map',
    'combat',
    'labels',
    'details',
    'compositemap',

    'alone',
    'aztec',
    'bark',
    'books',
    'chest',
    'coins',
    'crag',
    'cross',
    'dark',
    'door',
    'dream',
    'egypt',
    'gaol',
    'iban',
    'key',
    'keys',
    'lair',
    'lava',
    'logo',
    'main',
    'march',
    'mesh',
    'moody',
    'mummy',
    'nomad',
    'null',
    'pen',
    'quest',
    'regal',
    'roof',
    'roof2',
    'runes',
    'saga',
    'shine',
    'stars',
    'start',
    'theme',
    'achey',
    'accept',
    'acorn',
    'ahrims',
    'advice',
    'ambush',
    'anger1',
    'anger2',
    'anger3',
    'anger4',
    'anger5',
    'anger6',
    'anger7',
    'anger8',
    'anger9',

    // archive 3 (interfaces)
    'agilityarena_overlay',
    'agilityarena_trade',
    'ahoy_blackout',
    'ahoy_islandmap',
    'ahoy_runedraw',
    'ahoy_windspeed',
    'aide_compass',
    'aide_death',
    'anma_rgb',
    'area_task',
    'bank_charge_zmi',
    'bank_deposit_box',
    'bank_v2_help',
    'bank_v2_main',
    'bank_v2_side',
    'bankpin_main',
    'bankpin_settings',
    'banner_anti_virus',
    'banner_chatheads',
    'banner_easter08',
    'banner_group',
    'banner_group_assist',
    'banner_halloween',
    'banner_padlock_keys',
    'banner_poh',
    'banner_scamming',
    'banner_security',
    'banner_summoning',
    'banner_xmas',
    'barbassault_horn',
    'barbassault_over_att',
    'barbassault_over_col',
    'barbassault_over_def',
    'barbassault_over_heal',
    'barbassault_playerstat',
    'barbassault_reward_shop',
    'barbassault_timer_overlay',
    'barbassault_turret',
    'barbassault_tutorial',
    'barbassault_wavecomplete',
    'barrows_overlay',
    'barrows_puzzle',
    'blast_furnace_bar_stock',
    'blast_furnace_plan_scroll',
    'blast_furnace_temp_gauge',
    'boardgames_challenge',
    'boardgames_draughts',
    'boardgames_draughts_options',
    'boardgames_draughts_overlay',
    'boardgames_draughts_view',
    'boardgames_options',
    'boardgames_runelink',
    'boardgames_runelink_options',
    'boardgames_runelink_overlay',
    'boardgames_runelink_view',
    'boardgames_runesquares',
    'boardgames_runesquares_options',
    'boardgames_runesquares_overlay',
    'boardgames_runesquares_view',
    'boardgames_runeversi',
    'boardgames_runeversi_options',
    'boardgames_runeversi_overlay',
    'boardgames_runeversi_view',
    'bob_locator_amulet',
    'bounty_overlay',
    'bounty_overlay_waiting',
    'bounty_warning',
    'brain_cat_overlay',
    'brain_gas_overlay',
    'brain_water_overlay',
    'brew_game_over',
    'brew_overlay',
    'brew_telescope_overlay',
    'brew_tools',
    'brew_worktable',
    'burgh_map',
    'canoe',
    'canoe_stations_map',
    'canoe_travel',
    'carpet_draughts',
    'carpet_info',
    'carpet_main',
    'carpet_runelink',
    'carpet_runesquares',
    'carpet_runeversi',
    'carpet_ticket',
    'castlewars_catapult',
    'castlewars_score',
    'castlewars_shopside',
    'castlewars_status_overlay',
    'castlewars_status_overlay_saradomin',
    'castlewars_status_overlay_zamorak',
    'castlewars_trade',
    'cat_naming',
    'cave_goblin_markers',
    'champions_scroll',
    'chat_np1',
    'chat_np2',
    'chat_np3',
    'chat_np4',
    'chat1',
    'chat2',
    'chat3',
    'chat4',
    'chatdefault',
    'chatlarge',
    'chattop',
    'clanjoin',
    'clansetup',
    'clanwars_end',
    'clanwars_overlay',
    'clanwars_setup',
    'clanwars_setup_side',
    'clanwars_viewing_orb',
    'confirm_destroy',
    'contact_scroll_blood',
    'cooking_churn_op1',
    'cooking_churn_op2',
    'cooking_churn_op3',
    'crafting_glass',
    'crafting_gold',
    'crafting_silver_casting',
    'crafting_spinning',
    'crcs_equipment',
    'crcs_rewards',
    'crcs_scoreboard',
    'crcs_side',
    'crcs_tightrope',
    'credit_shop',
    'cws_doomsayer',
    'cws_warning_1',
    'cws_warning_10',
    'cws_warning_11',
    'cws_warning_12',
    'cws_warning_13',
    'cws_warning_14',
    'cws_warning_15',
    'cws_warning_16',
    'cws_warning_17',
    'cws_warning_18',
    'cws_warning_19',
    'cws_warning_2',
    'cws_warning_20',
    'cws_warning_21',
    'cws_warning_23',
    'cws_warning_24',
    'cws_warning_25',
    'cws_warning_26',
    'cws_warning_27',
    'cws_warning_28',
    'cws_warning_29',
    'cws_warning_3',
    'cws_warning_30',
    'cws_warning_4',
    'cws_warning_5',
    'cws_warning_6',
    'cws_warning_8',
    'cws_warning_9',
    'darkness_dark',
    'darkness_light',
    'darkness_medium',
    'death_dice',
    'deep_blue',
    'doubleobjbox',
    'dragon_slayer_qip_clouds',
    'dragon_slayer_qip_cr_journey',
    'dragon_slayer_qip_elvarg',
    'dragon_slayer_qip_elvarg_fly',
    'dragon_slayer_qip_map',
    'dream_armour',
    'dream_cyrisus',
    'dream_monster_stat',
    'dream_player_stats',
    'dream_title',
    'duel2_challengeoverlay',
    'duel2_scoreboard',
    'duel2_select_type',
    'duel2_side',
    'dwarf_rock_book',
    'dwarf_rock_cannon',
    'dwarf_rock_schematics',
    'dwarf_rock_schematics_control',
    'emotes',
    'enakh_film',
    'enakh_smoke_overlay',
    'equip_screen2',
    'exchange_history',
    'exchange_itemsets',
    'exchange_sand_timer',
    'exchange_sets_side',
    'fade_from_black',
    'fade_from_white',
    'fade_to_black',
    'fade_to_light_blue',
    'fade_to_white',
    'fairy_certificate',
    'fairy2_certificate_broken',
    'fairy2_message',
    'farming_tools',
    'farming_tools_side',
    'favour_keyring',
    'filterbuttons',
    'friends2',
    'garden_list',
    'garden_quiz',
    'glidermap',
    'gnomeball',
    'godwars_overlay',
    'graphics_options',
    'gravestone_shop',
    'grim_tasklist',
    'guide_eggs_overlay',
    'guide_flour_overlay',
    'guide_inv_flour',
    'guide_milk_overlay',
    'hauntedmine_controls',
    'heat_overlay',
    'horror_metaldoor',
    'ignore2',
    'inventory',
    'inventory_ranging',
    'inventory_wear',
    'inventory_wear2',
    'keldagrim_map',
    'keldagrim_story1',
    'keldagrim_titles',
    'kings_letter_v2',
    'kr_king_statue',
    'kr_picklock',
    'kr_pyramid_escape',
    'leather_crafting',
    'legends_mirror',
    'light_blue',
    'light2',
    'lightning_flash',
    'loginscreen',
    'logout',
    'lore_bank',
    'lore_bank_side',
    'lore_cats_side',
    'lore_stats_side',
    'lotr_scroll',
    'luc2_chapter1',
    'luc2_chapter2',
    'luc2_chapter3',
    'luc2_lucien_projectiles',
    'luc2_telescope_view',
    'macro_combilock',
    'macro_evil_bob',
    'macro_mime_emotes',
    'macro_quizshow',
    'magic',
    'magic_lunar',
    'magic_zaros',
    'magictraining_grave',
    'magictraining_shop',
    'magictraining_tele',
    'mazetimer',
    'mcannon_interface',
    'message_np1',
    'message_np2',
    'message_np3',
    'message_np4',
    'message_np5',
    'message1',
    'message2',
    'message3',
    'message4',
    'message5',
    'messagescroll',
    'messagescroll2',
    'misc_shipjourney',
    'mm_message',
    'mole_mud',
    'mourning_deathalter_list',
    'multi2',
    'multi2_chat',
    'multi2_mes',
    'multi3',
    'multi3_chat',
    'multi4',
    'multi4_chat',
    'multi5',
    'multi5_chat',
    'multivar2',
    'multivar3',
    'multivar4',
    'multivar5',
    'music_v3',
    'myq3_blackout',
    'myq3_boat_map',
    'myq3_statue_painting',
    'noexit',
    'npcchat_np1',
    'npcchat_np2',
    'npcchat_np3',
    'npcchat_np4',
    'npcchat1',
    'npcchat2',
    'npcchat3',
    'npcchat4',
    'npcchatlarge',
    'ntk_overlay',
    'objbox',
    'objdialog',
    'olaf2_lock_gate',
    'olaf2_skull_puzzle',
    'olaf2_treasuremap',
    'openurl',
    'options',
    'paint_cannon',
    'pattern_cards',
    'pattern_next',
    'peng_emote',
    'pest_lander_overlay',
    'pest_mace',
    'pest_rewards',
    'pest_status_overlay',
    'pinball_interface',
    'pmchat',
    'poh_hangman',
    'poh_hangman_german',
    'poh_house_options',
    'poh_magic_tablets',
    'poh_ranging',
    'poh_sawmill',
    'poh_scrying_pool',
    'prayer',
    'priestperil_gravemonument',
    'prisonpete',
    'quest_complete_scroll',
    'questjournal_scroll',
    'questjournal_v2',
    'quickchat_locked',
    'quickchat_tutorial',
    'rabbit_overlay',
    'rabbit_shop',
    'ratcatcher_flute',
    'ratcatcher_flute_music',
    'ratcatcher_overlay',
    'rcguild_map',
    'rcguild_overlay',
    'rcguild_rewards',
    'rcguild_side',
    'rd_combolock',
    'regicide_still',
    'rocko_cannonball',
    'rocko_kittens',
    'rocko_seagull',
    'rocko_underwater',
    'roguesden_dials',
    'roguesden_gear_select',
    'roguesden_gears',
    'roguesden_puzzle',
    'rum_deal_title',
    'sailing_transport_world_map',
    'sandstorm',
    'sc_item_transfer',
    'sc_processing',
    'sc_remaining_clay',
    'sc_reward_shop',
    'sc_scores',
    'sc_scores_border',
    'sc_tutorial_overlay',
    'scroll_godfather',
    'seaslug_boat_travel',
    'seer_combolock',
    'shop_template',
    'shop_template_side',
    'skill_cookmany',
    'skill_guide_v2',
    'skill_multi1',
    'skill_multi1_small',
    'skill_multi6',
    'slayer_staff_spells',
    'smelting',
    'smithing_new',
    'smki_assignment',
    'smki_buy',
    'smki_learn',
    'smki_smoke_overlay',
    'smokeoverlay',
    'snapshot_main',
    'soulbane_angerbar',
    'soulbane_cut',
    'soulbane_darkness',
    'soulbane_scare',
    'sound_options',
    'staff_spells',
    'stats',
    'statusicons',
    'stockcollect',
    'stockmarket',
    'stockside',
    'summoning_side',
    'surok_letter1',
    'surok_letter2',
    'swamp_boatjourney',
    'swamp_boatjourney_back',
    'tanner',
    'target',
    'teleport_other',
    'temple_screen',
    'templetrek_map',
    'thessalia_clothes_female',
    'thessalia_clothes_male',
    'tog_water_bowl',
    'tol_cage_puzzle',
    'tol_homonculus_overlay',
    'tol_pipe_machine',
    'tol_pressure_machine',
    'toplevel',
    'toplevel_full',
    'toplevel_fullscreen',
    'topstat_hitpoints',
    'topstat_lore',
    'topstat_prayer',
    'topstat_run',
    'tradeconfirm',
    'trademain',
    'tradeside',
    'trail_cluelong',
    'trail_map01',
    'trail_map02',
    'trail_map03',
    'trail_map04',
    'trail_map05',
    'trail_map06',
    'trail_map07',
    'trail_map08',
    'trail_map09',
    'trail_map10',
    'trail_map11',
    'trail_map12',
    'trail_map13',
    'trail_map14',
    'trail_map15',
    'trail_map16',
    'trail_map17',
    'trail_puzzle',
    'trail_reward',
    'trail_sextant',
    'trawler_overlay',
    'trawler_reward',
    'trawler_start',
    'tutorial_progress',
    'tutorial_text',
    'tutorial_text2',
    'tutorial2_death',
    'tutorial2_mesbox',
    'tutorial2_objbox',
    'tutorial2_switch_task',
    'tutorial2_text',
    'tzhaar_fightpit',
    'vm_digsite',
    'vm_kudos',
    'vm_museum_map',
    'vm_timeline',
    'warguild_defence',
    'warguild_defence_mini',
    'warguild_dummy',
    'weapon_2h_sword_sel',
    'weapon_baxe_sel',
    'weapon_bow_sel',
    'weapon_chinchompa_sel',
    'weapon_claws_sel',
    'weapon_dagger_sel',
    'weapon_fists_sel',
    'weapon_fixed_device_sel',
    'weapon_halberd_sel',
    'weapon_mace_sel',
    'weapon_pickaxe_sel',
    'weapon_salamander_sel',
    'weapon_scepter_sel',
    'weapon_scimitar_sel',
    'weapon_scythe_sel',
    'weapon_spear_sel',
    'weapon_staff_sel',
    'weapon_thrown_sel',
    'weapon_warhammer_sel',
    'weapon_whip_sel',
    'weapon_xbow_sel',
    'welcome_final_tex',
    'welcome_screen',
    'werewolf_goal',
    'wilderness_overlay',
    'wilderness_warning',
    'wom_scroll',
    'wom_telescope',
    'worldmap',
    'wornitems',
    'xbows_enchant_bolt',
    'xbows_pouch',
    'zep_balloon_map',
    'zep_interface',
    'zep_interface_side',

    // archive 8 (binary)
    'huffman',
];

console.time('Imported extra names');
// seed with known names from OSRS
import fs from 'fs';
fs.readFileSync('osrs.tsv', 'ascii').split('\n').forEach(x => {
    let parts = x.split('\t');
    if (parts.length > 3 && parts[4].length && KNOWN_NAMES.indexOf(parts[4]) === -1) {
        KNOWN_NAMES.push(parts[4]);
    }
});
console.timeEnd('Imported extra names');

console.time('Imported 2004 names');
let oldList = [// title
    'index.dat',
    'logo.dat',
    'p11.dat',
    'p12.dat',
    'b12.dat',
    'q8.dat',
    'runes.dat',
    'title.dat',
    'titlebox.dat',
    'titlebutton.dat',
    // seen in 274
    'p11_full.dat',
    'p12_full.dat',
    'b12_full.dat',
    'q8_full.dat',

    // config
    'flo.dat',
    'flo.idx',
    'idk.dat',
    'idk.idx',
    'loc.dat',
    'loc.idx',
    'npc.dat',
    'npc.idx',
    'obj.dat',
    'obj.idx',
    'seq.dat',
    'seq.idx',
    'spotanim.dat',
    'spotanim.idx',
    'varp.dat',
    'varp.idx',
    // seen in 254
    'varbit.dat',
    'varbit.idx',
    // seen in 274
    'mesanim.dat',
    'mesanim.idx',
    'mes.dat',
    'mes.idx',
    'param.dat',
    'param.idx',
    'hunt.dat',
    'hunt.idx',

    // interface
    'data',

    // media
    'backbase1.dat',
    'backbase2.dat',
    'backhmid1.dat',
    'backhmid2.dat',
    'backleft1.dat',
    'backleft2.dat',
    'backright1.dat',
    'backright2.dat',
    'backtop1.dat',
    'backtop2.dat',
    'backvmid1.dat',
    'backvmid2.dat',
    'backvmid3.dat',
    'chatback.dat',
    'combatboxes.dat',
    'combaticons.dat',
    'combaticons2.dat',
    'combaticons3.dat',
    'compass.dat',
    'cross.dat',
    'gnomeball_buttons.dat',
    'headicons.dat',
    'hitmarks.dat',
    // index.dat
    'invback.dat',
    'leftarrow.dat',
    'magicoff.dat',
    'magicoff2.dat',
    'magicon.dat',
    'magicon2.dat',
    'mapback.dat',
    'mapdots.dat',
    'mapflag.dat',
    'mapfunction.dat',
    'mapscene.dat',
    'miscgraphics.dat',
    'miscgraphics2.dat',
    'miscgraphics3.dat',
    'prayerglow.dat',
    'prayeroff.dat',
    'prayeron.dat',
    'redstone1.dat',
    'redstone2.dat',
    'redstone3.dat',
    'rightarrow.dat',
    'scrollbar.dat',
    'sideicons.dat',
    'staticons.dat',
    'staticons2.dat',
    'steelborder.dat',
    'steelborder2.dat',
    'sworddecor.dat',
    'tradebacking.dat',
    'wornicons.dat',
    // seen in 254
    'mapmarker.dat',
    'mod_icons.dat',
    'mapedge.dat',
    // seen in 336
    'blackmark.dat',
    'button_brown.dat',
    'button_brown_big.dat',
    'button_red.dat',
    'chest.dat',
    'coins.dat',
    'headicons_hint.dat',
    'headicons_pk.dat',
    'headicons_prayer.dat',
    'key.dat',
    'keys.dat',
    'leftarrow_small.dat',
    'letter.dat',
    'number_button.dat',
    'overlay_duel.dat',
    'overlay_multiway.dat',
    'pen.dat',
    'rightarrow_small.dat',
    'startgame.dat',
    'tex_brown.dat',
    'tex_red.dat',
    'titlescroll.dat',

    // models (225 and before)
    'base_head.dat',
    'base_label.dat',
    'base_type.dat',
    'frame_del.dat',
    'frame_head.dat',
    'frame_tran1.dat',
    'frame_tran2.dat',
    'ob_axis.dat',
    'ob_face1.dat',
    'ob_face2.dat',
    'ob_face3.dat',
    'ob_face4.dat',
    'ob_face5.dat',
    'ob_head.dat',
    'ob_point1.dat',
    'ob_point2.dat',
    'ob_point3.dat',
    'ob_point4.dat',
    'ob_point5.dat',
    'ob_vertex1.dat',
    'ob_vertex2.dat',

    // versionlist (introduced in 234)
    'anim_crc',
    'anim_index',
    'anim_version',
    'map_crc',
    'map_index',
    'map_version',
    'midi_crc',
    'midi_index',
    'midi_version',
    'model_crc',
    'model_index',
    'model_version',

    // textures
    // index.dat
    '0.dat',
    '1.dat',
    '2.dat',
    '3.dat',
    '4.dat',
    '5.dat',
    '6.dat',
    '7.dat',
    '8.dat',
    '9.dat',
    '10.dat',
    '11.dat',
    '12.dat',
    '13.dat',
    '14.dat',
    '15.dat',
    '16.dat',
    '17.dat',
    '18.dat',
    '19.dat',
    '20.dat',
    '21.dat',
    '22.dat',
    '23.dat',
    '24.dat',
    '25.dat',
    '26.dat',
    '27.dat',
    '28.dat',
    '29.dat',
    '30.dat',
    '31.dat',
    '32.dat',
    '33.dat',
    '34.dat',
    '35.dat',
    '36.dat',
    '37.dat',
    '38.dat',
    '39.dat',
    '40.dat',
    '41.dat',
    '42.dat',
    '43.dat',
    '44.dat',
    '45.dat',
    '46.dat',
    '47.dat',
    '48.dat',
    '49.dat',

    // wordenc
    'badenc.txt',
    'domainenc.txt',
    'fragmentsenc.txt',
    'tldlist.txt',

    // sounds
    'sounds.dat'
];
for (let i = 0; i < oldList.length; i++) {
    if (KNOWN_NAMES.indexOf(oldList[i]) === -1) {
        KNOWN_NAMES.push(oldList[i]);
    }

    let noExtension = oldList[i].split('.')[0];
    if (KNOWN_NAMES.indexOf(noExtension) === -1) {
        KNOWN_NAMES.push(noExtension);
    }
}
console.timeEnd('Imported 2004 names');

// append ,num to all names to find sprite groups
console.time('Generated sprite group names');
let len = KNOWN_NAMES.length;
for (let i = 0; i < len; i++) {
    let name = KNOWN_NAMES[i];
    if (name.indexOf(',') === -1) {
        continue;
    }

    name = name.split(',')[0];
    for (let j = 0; j < 100; j++) {
        KNOWN_NAMES.push(`${name},${j}`);
    }
}
console.timeEnd('Generated sprite group names');

console.time('Generated hash list');
// unnamed components inherit their name from their index
for (let i = 0; i < 512; i++) {
    KNOWN_NAMES.push(`com_${i}`);
    KNOWN_NAMES.push(`com${i}`);
}

// some loosely named components can be named "a0", "a1", "a2", etc.
for (let a = 0; a < 26; a++) {
    for (let b = 0; b < 7; b++) {
        KNOWN_NAMES.push(`${String.fromCharCode(97 + a)}${b}`);
    }
}

// some loosely named components can be named "a", "b", "c", etc.
for (let a = 0; a < 26; a++) {
    KNOWN_NAMES.push(`${String.fromCharCode(97 + a)}`);
}

// some components are just an arbitrary number
for (let i = 0; i < 256; i++) {
    KNOWN_NAMES.push(`${i}`);
}

// map files
for (let x = 0; x < 200; x++) {
    for (let z = 0; z < 200; z++) {
        KNOWN_NAMES.push(`m${x}_${z}`);
        KNOWN_NAMES.push(`l${x}_${z}`);
        KNOWN_NAMES.push(`n${x}_${z}`);
        KNOWN_NAMES.push(`e${x}_${z}`);
        KNOWN_NAMES.push(`um${x}_${z}`);
        KNOWN_NAMES.push(`ul${x}_${z}`);
    }
}
console.timeEnd('Generated hash list');

export const KNOWN_HASHES = {};

export function hashCode(str) {
    str = str.toString();

    let hash = 0;
    str = str.toLowerCase();
    for (let i = 0; i < str.length; i++) {
        hash = ((hash << 5) + str.charCodeAt(i) - hash) | 0;
    }
    return hash;
}

console.time('Generated name hashes');
for (let i = 0; i < KNOWN_NAMES.length; i++) {
    let name = KNOWN_NAMES[i];
    let hash = hashCode(name);
    KNOWN_HASHES[hash] = name;
}
console.timeEnd('Generated name hashes');
